[package]
name = "{{plug_slug}}_component"
edition = "2021"
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
itertools = "0.13.0"
conformal_component = {{{crate_version}}}
conformal_poly = {{{crate_version}}}
