[package]
name = "{{plug_slug}}_component"
edition = "2021"
rust-version = "1.79.0"
publish = false

[dependencies]
itertools = "0.13.0"
conformal_component = {{{crate_version}}}
conformal_poly = {{{crate_version}}}
