[package]
name = "preferences"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.117"

[features]
test-utils = []

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"
